studiowartenbergh/routes/blueprints/admin.py
import os
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for,
    current_app as app,
)
from werkzeug.utils import secure_filename
from sqlite3 import IntegrityError
from collections import defaultdict

from .auth import login_required

from studiowartenbergh.db import get_db

bp = Blueprint('admin', __name__, url_prefix='/admin')


def content_id_from_title(session, title):
    return session.execute(
        'SELECT id FROM content WHERE title = ?',
        (request.form['title'], )  # title is unique
    ).fetchone()['id']


def content_from_id(session, content_id):
    result = dict(session.execute(
        'SELECT * FROM content WHERE id = ?',
        (content_id,)
    ).fetchone())

    result['images'] = [
        dict(x) for x in session.execute(
            'SELECT * FROM image WHERE content_id = ? ',
            (content_id,)
        ).fetchall()
    ]

    return result


def content_list(session):
    return session.execute('SELECT id, title from content').fetchall()


def add_images(session, request, content_id):
    """
    Add files to the filesystem where necessary.
    Queue entries to the db for the corresponding content.
    """
    for img in request.files.getlist('image'):
        fname = secure_filename(img.filename)
        abspath = os.path.join(app.static_folder, fname)

        if not os.path.isfile(abspath):
            img.save(abspath)

        try:
            session.execute(
                'INSERT INTO image (content_id, filename) VALUES (?, ?)',
                (content_id, fname)
            )
        except IntegrityError as e:
            # Image is already added to content
            print("Image added twice to content ", e)

    return session


def remove_images(session, image_ids):
    """
    Remove images from filesystem where necessary.
    Remove corresponding entries in db.

    :param session: sqlite3.Connection
    :param image_ids: list of image_ids
    """
    for image_id in image_ids:
        fname = session.execute(
            'SELECT filename FROM image WHERE id = ?',
            (image_id, )
        ).fetchone()['filename']

        last_item = session.execute(
            'SELECT COUNT(*) FROM image WHERE filename = ?',
            (fname,)
        ).fetchone()[0] <= 1

        session.execute(
            'DELETE FROM image WHERE id = ?',
            (image_id, )
        )

        # Only remove the file if its the last entry
        if last_item:
            abspath = os.path.join(app.static_folder, fname)

            if os.path.isfile(abspath):
                os.remove(abspath)

    return session


@bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    """
    Template that renders a list of content items and
    a modification / creation form.
    Optionally populates form with content data.
    """
    selected_content = defaultdict(lambda: "")
    session = get_db()

    if request.method == 'POST':
        content_id = request.form['content_select']
        session = get_db()
        selected_content = content_from_id(session, content_id)

    _content_list = content_list(session)
    return render_template(
        'admin_base.html',
        content_list=_content_list,
        selected_content=selected_content
    )


@bp.route('/submit_content', methods=['POST'])
@login_required
def submit_content():
    """
    Endpoint for creating or modifying content
    """
    content_id = request.form['content_id']
    session = get_db()

    if content_id == '':
        session.execute(
            'INSERT INTO content (title, body)'
            'VALUES (?, ?)',
            (request.form['title'], request.form['body'])
        )
        session.commit()
        content_id = content_id_from_title(session, request.form['title'])
    else:
        session.execute(
            'UPDATE content SET title = ?, body = ?'
            'WHERE id = ?',
            (request.form['title'], request.form['body'], content_id)
        )
    session = add_images(session, request, content_id)
    session.commit()

    return render_template(
        'admin_base.html',
        content_list=content_list(session),
        selected_content=content_from_id(session, content_id)
    )


@bp.route('/<int:image_id>/<int:content_id>/delete_image', methods=['GET'])
def delete_image(image_id, content_id):
    session = get_db()
    session = remove_images(session, [image_id])
    session.commit()
    return render_template(
        'admin_base.html',
        content_list=content_list(session),
        selected_content=content_from_id(session, content_id)
    )


@bp.route('/delete_content', methods=['POST'])
def delete_content():
    content_id = request.form['content_id']

    session = get_db()
    session.execute("DELETE FROM content WHERE id = ?", (content_id, ))
    session = remove_images(session, request.form.getlist('image'))
    session.commit()

    return redirect(url_for('admin.index'))

studiowartenbergh/routes/blueprints/auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

from studiowartenbergh.db import get_db

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']
        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif db.execute(
            'SELECT id FROM user WHERE username = ?', (username,)
        ).fetchone() is not None:
            error = 'User {} is already registered.'.format(username)
        if not email:
            email = ''

        if error is None:
            db.execute(
                'INSERT INTO user (username, password, email) VALUES (?, ?, ?)',
                (username, generate_password_hash(password), email)
            )
            db.commit()
            return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.html')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        user = db.execute(
            'SELECT * FROM user WHERE username = ?', (username,)
        ).fetchone()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('admin.index'))

        flash(error)

    return render_template('auth/login.html')


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE id = ?', (user_id,)
        ).fetchone()


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

studiowartenbergh/templates/admin_base.html
<!doctype html>
<title>{% block title %}{% endblock %} - Studio Wartenbergh</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <ul>
      {% if g.user %}
        <li>
            <span>Logged in as {{ g.user['username'] }}</span>
        </li>
        <li>
            <a href="{{ url_for('auth.logout') }}">
                Log Out
            </a>
        </li>
      {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}
        <h2> Content submission / modification </h2>
    {% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
        <div class="flash">
            {{ message }}
        </div>
  {% endfor %}
  {% block content %}
  {% if content_list %}
    <form method="post" action={{ url_for("admin.index") }} id="content_form">
        <select id="content_select" name="content_select" form="content_form">
            {% for content_item in content_list %}
            <option value={{ content_item['id'] }} {% if content_item['id'] == selected_content['id']  %}selected{% endif %}>
                        {{ content_item['title'] }}
                    </option>
            {% endfor %}
        </select>
        <input type="submit">
    </form>
  {% else %}
    No content found
  {% endif %}
  {% if selected_content['id'] %}
    <p>
        Now editing <span style='color:blue'>{{ selected_content['title'] }}</span><br>
        <a href={{ url_for('admin.index') }}>
            Reset<br>
        </a>
    </p>
  {% endif %}
  <form method="post" action={{ url_for("admin.submit_content")}} id="content_form" enctype=multipart/form-data>
    <input type="hidden" name="content_id" id="content_id" value={{ selected_content['id'] }}>
    <label for="title">Title</label>
    <input type="title" name="title" id="title" value={{ selected_content['title'] }}>
    <label for="body">Text</label>
    <textarea name="body" id="body">{{ selected_content['body'] }}</textarea>
    {% if selected_content['images']  %}
        {% for image in selected_content['images'] %}
            <img class="thumbnail" src={{ url_for('static', filename=image['filename']) }}>
            <a class='button' href={{ url_for('admin.delete_image', image_id=image['id'], content_id=selected_content['id']) }}>
                Delete {{ image['filename'] }}
            </a>
        {% endfor %}
    {% endif %}
    <label for="image">Add image</label>
    <input type="file" class="image_input" name="image" accept="image/*" multiple>
    <input type="submit" value="Save changes" style="color:green">
  </form>
  {% if selected_content['id'] %}
  <form action={{ url_for("admin.delete_content") }} method="post">
      {% for image in selected_content['images'] %}
        <input type="hidden" name="image" id="image" value={{ image['id'] }}>
     {% endfor %}
     <input type="hidden" name="content_id" id="content_id" value={{ selected_content['id'] }}>
     <input type="submit" value="Delete {{ selected_content['title']}}" style="color:red">
  </form>
  {% endif %}
  {% endblock %}
</section>

studiowartenbergh/templates/base.html
<!doctype HTML>
<html>
<title>{% block title %}{% endblock %} Studio Wartenbergh</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</body>
<img class='site-header-image' src={{ url_for('static', filename='header.png')}}>
<div class='site-header-container'>
    <nav>
        {% if g.user %}
        <h3>Authentication</h3>
        <ul>
            <li><span>Logged in as {{ g.user['username'] }}</span>
            <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
        </ul>
        {% endif %}
        <ul class='header-menu'>
            <li class='header-menu-item'><a href='/'>Home</a></li>
            <li class='header-menu-item'><a href='/about'>About me</a></li>
            <li class='header-menu-item'><a href='/contact'>Contact</a></li>
        </ul>
    </nav>
    <p>studio Wartenbergh</p>
</div>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>
</body>
</html>

studiowartenbergh/templates/home.html
{% extends 'base.html' %}
{% block header %}
<script type='text/javascript' src={{ url_for('static', filename='manage_homepage.js') }}></script>
{% endblock %}
{% block content %}
<div class='modal'>
</div>
<div class='items-playground'>
    <div class='item-container' id="ic0">
        <div class='full-item' id="ic0">
            <p> 
            Immaterialicious was een samenwerking tussen Nederlandse modelabels en programmeurs. Tijdens het makersprogramma gingen we op zoek naar de mogelijkheden van een digitale mode-identiteit. Wat is mode zonder het lichaam? Of hoe kan het lichaam een hele nieuwe rol vervullen?

                <img align=left' name='immaterialicious' class='image' src={{ url_for('static', filename='immaterialicious1.png') }}>

                De uitkomsten van het makersprogramma waren te zien tijdens het Immaterialicious event in 
                <a href=https://dezwijger.nl/programma/immaterialicious>Pakhuis de Zwijger.</a>
                <img align='left' class='image' src={{ url_for('static', filename='immaterialicious2.png') }}>
            </p>
        </div>
        <div class='item-abstract-large'>
            <img align=left' name='immaterialicious' class='image' src={{ url_for('static', filename='immaterialicious1.png') }}>
            <p>immaterialicious</p>
        </div>
    </div>
    <div class='item-container' id="ic1">
        <div class='full-item' id="ic1">
            <p>
            Voorstel voor een nieuwe manier van kamperen. De structuur opent zich rondom een as waardoor de leefruimte verdubbeld. 
            <img align='left' name='caravan' class='image' src={{ url_for('static', filename='Caravan1.png') }}>
            Verder kunnen verschillende panelen openklappen en krijgen een nieuwe functie toebedeeld
            <img align='left' class='image' src={{ url_for('static', filename='Caravan2.png') }}>
            </p>
        </div>
        <div class='item-abstract-medium'>
            <img align='left' name='caravan' class='image' src={{ url_for('static', filename='Caravan1.png') }}>
            <p>caravan</p>
        </div>
    </div>
    <div class='item-container' id="ic2">
        <div class='full-item' id="ic2">
            <p>
            “De uitgebreidheid van onze kosmos hangt af van [onze] eigen ontvankelijkheid. Op eigen instelling komt het aan; de dingen krijgen slechts waarde voor ons voor zover wij ze kunnen bevatten.”

            Gerrit Thomas Rietveld

            Afstudeertentoonstelling Gerrit Rietveld Academie 5/7/2017 – 9/7/2017

            <img name='lonely rietveld' class='image-large' src={{ url_for('static', filename='lonelyrietveld.jpeg') }}>

            Tussen de werken van alle afgestudeerde studenten nodigt Lonely Rietveld de bezoeker uit om het gebouw op een hele nieuwe wijze te ervaren.
            Verborgen holtes, meeslepende verhalen en banale schoonheden die tot noch toe onderbelicht zijn gebleven komen aan het licht door middel van een publicatie en ruimtelijke interventies in en om het ‘oude gebouw’ van de Academie.
            </p>
        </div>
        <div class='item-abstract-small'>
            <img name='lonely rietveld' class='image' src={{ url_for('static', filename='lonelyrietveld.jpeg') }}>
            <p>lonely rietveld</p>
        </div>
    </div>
    <div class='item-container' id="ic3">
        <div class='full-item' id="ic3">
            <p>
            Threshold

            Het kastje met twee gezichten.

            Mystieke bijgeloven, geheime brieven, obscure souvenirs of een stoffige verzameling ansichtkaarten. Het is nooit zeker wat iemand in zijn geheime laatje heeft liggen.  Het ontvouwd een wereld die om een bepaalde reden liever niet gedeeld wordt met anderen. 

            In deze tijd waar privacy een privilege begint te worden is het des te belangrijker dat de grens tussen privé en publiek blijft bestaan. Of dat men op zijn minst bewust is van deze keus.

            Threshold speelt met deze tweedeling en vraagt aan de gebruiker: ‘Wat laat je zien en wat stop je weg?”

            Op het eerste gezicht lijkt het object een schattig kastje. De spiegelende achterwand laat de draadstalen constructies zweven en geeft een ruimtelijk effect. 

            Deze optische illusie verhuld  een oase die alleen gevonden kan worden door diegene die weet van zijn bestaan.
            <img name='threshold' class='image' src={{ url_for('static', filename='threshold1.jpeg') }}>

            

            The cabinet with two faces.

            Mystical superstitions, secret letters, obscure keepsakes or a dusty collection of postcards. What is kept in someone’s dark corner is never certain. A secret world that prefers to stay put in the dark and doesn’t like others creeping around. 

            In this age where privacy starts to become a privilege, the line between what is public and what is private gradually decreases. In some cases it feels like that there is no choice at all. 

            Threshold plays with this twofold. It makes it very clear and demands the user to make a choice: ‘What do you want to display and what can be tucked away?’

            In a first glance the object seems to be a charming cabinet. The mirrored back wall makes the coated metal constructions float in space and has a fascinating spacious effect. This optical illusion generates the space for the inside world that is only found by these who know of its existence.
            <img class='image' src={{ url_for('static', filename='threshold2.jpeg') }}>

            Threshold.
            Oplage van 5
            Nog 4 beschikbaar.
            50x50x14
            Hout, acrylaat, koper
            </p>
        </div>
        <div class='item-abstract-medium'>
            <img name='threshold' class='image' src={{ url_for('static', filename='threshold1.jpeg') }}>
            <p>threshold</p>
        </div>
    </div>
    <div class='item-container' id="ic4">
        <div class='full-item' id="ic4">
            <p>
            Traces

            In hoeverre spelen de details van alledag nog een rol in een maatschappij waar alles schreeuwt om aandacht?
            De behoefte en het vermogen je te verwondere lijken hoofdzakelijk te zijn weggelegd voor verre reizen, buitensporige omstandigheden en plekken zoals musea en theaters.

            Tijdens de intensieve zoektocht naar uitzonderlijkheid wordt de schoonheid van het alledaagse al snel over het hoofd gezien. De betekenis van het gewone afgedaan als futiel. Het gegeven irrelevant. Het gangbare bijna vijandig. 

            In Traces maakt de kunstenaar zich sterk voor de schoonheid van het banale. De sporen van een stuk ducktape, achtergelaten door een haastige gebruiker, is het startpunt geworden van een serie schilderijtjes. De patronen zijn exacte kopieën van afgerukte stukken tape, elk kussentje met zorg gereproduceerd in bladgoud. Een gedaanteverandering die het imago van het onderwerp totaal veranderd. Een braille-achtige taal onthult zich naar mate je er langer naar blijft kijken. 
            <img class='image' src={{ url_for('static', filename='traces121x15.jpeg') }}>

            In a society where everything screams for attention, what role is destined for the details of our daily life?

            The need and ability to be amazed seem exclusive components of remote travels, flamboyant happenings and places destined to extract these emotions, like musea and theaters.

            But amid this search for idiosyncratic phenomenas, the world of everyday is often overlooked. 
            <img class='image' src={{ url_for('static', filename='traces221x15.jpeg') }}>

            The implication of the accustomed seems dull. The given insignificant. The common nearly hostile.

            In Traces, the artist tries to show the beauty of the ordinary. Traces of duck-tape left behind by its user are the starting point of a series of paintings. The patterns are exact copies of torn off scraps of tape. Every particle carefully reproduced in gold leaf. A metamorphosis that changes the entire image of the subject. The Braille like pattern slowly uncovers itself to the attentive viewer. 
            <img class='image' src={{ url_for('static', filename='traces330x22.jpeg') }}>
            Taped Traces
            Serie van 4
            Bladgoud op papier
            <img class='image' src={{ url_for('static', filename='traces35x24SOLD.jpeg') }}>
            </p>
        </div>
        <div class='item-abstract-large'>
            <img class='image' src={{ url_for('static', filename='traces35x24SOLD.jpeg') }}>
            <p>traces</p>
        </div>
    </div>
    <div class='item-container' id="ic5">
        <div class='full-item' id="ic5">
            <p>
            <img class='image' src={{ url_for('static', filename='UCFurniture1.jpeg') }}>
            De UC-serie is een concept dat niet alleen in kasten werkt. Ook bedden, tafels en banken kunnen zo ontworpen worden. De constructie van metalen kolommen is dun, licht en ijzersterk.
            <img name='UC Furniture' class='image' src={{ url_for('static', filename='UCFurniture2.jpeg') }}>

            Prijs op aanvraag.
            <img class='image' src={{ url_for('static', filename='UCFurniture3.jpeg') }}>
            </p>
        </div>
        <div class='item-abstract-small'>
            <img name='UC Furniture' class='image' src={{ url_for('static', filename='UCFurniture2.jpeg') }}>
            <p>UC Furniture</p>
        </div>
    </div>
</div>
{% endblock %}